name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  expo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g expo-cli

      - name: Debug: whoami & version
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          expo whoami
          expo --version

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --token $EXPO_TOKEN

      - name: Start Expo build (Android APK)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo build:android -t apk --non-interactive

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: '*.apk'
